apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab07-app
  labels:
    app: lab07-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab07-app
  template:
    metadata:
      labels:
        app: lab07-app
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: lab07-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10