apiVersion: v1
kind: Service
metadata:
  name: lab07-service
spec:
  type: NodePort
  selector:
    app: lab07-app
  ports:
    - protocol: TCP
      port: 80 # порт Service
      targetPort: 80 # порт контейнера
      nodePort: 30080 # внешний порт узла